### ISSUE TITLE
Support sending vnstock data to Google Sheets

### ISSUE THREAD

**Issue by thinh-vu** [thinh-vu/vnstock#10]

**Comment by andrey-jef** [comment]
Hi,

Rất cảm ơn repo của b khi giới thiệu về các public API để lấy dữ liệu chứng khoán Vietnam. Trước giờ m hay dùng formula [IMPORTXML](https://support.google.com/docs/answer/3093342?hl=en) để cào dữ liệu giá đóng cửa cuối ngày từ cafef, mà bị lỗi hoài với vài mã cp (vd: NVL, VPB) do cafef thay đổi cấu trúc trang.

Vì feature `Support sending vnstock data to Google Sheets` này đang trong backlog, nên mình xin phép chia sẻ cách mình hiện dùng tạm `user-defined formula` (UDF) trong gsheets để lấy dữ liệu giá đóng cửa cuối ngày của 1 cổ phiếu, thông qua public API của TCBS mà bạn hướng dẫn trong vnstock.

B1: thông qua [Apps Script](https://developers.google.com/apps-script/guides/sheets), tạo 1 UDF để mình có thể gọi trực tiếp trong bảng tính gsheet, vd: `=getClosePrice($B2)`
```javascript
/**
 * getClosePrice(): get current Close Price of the specific stock.
 * This function used the public api from https://www.tcbs.com.vn/home
 * 
 * @param {String<string>} ticker of the specific stock.
 * @return {Number<number>} current Close Price of the stock;
 * 
 * @customfunction
 */
function getClosePrice(ticker) {
  const apiUrl = 'https://apipubaws.tcbs.com.vn/stock-insight/v1/stock/second-tc-price?tickers=' + ticker;
  const response = UrlFetchApp.fetch(apiUrl);
  const responseData = response.getContentText();
  const jsonResponse = JSON.parse(jsonResponse);
  const closePrice = jsonResponse.data[0].cp;

  return closePrice;
}
```

B2: thông qua Apps Script, tạo hàm `refreshUDF` và tạo 1 [daily trigger event](https://developers.google.com/apps-script/guides/triggers) để chỉ cập nhật dữ liệu giá đóng cửa hàng ngày trong tuần, vì sàn giao dịch đóng cửa vào cuối tuần.
```javascript
/**
 * Force refreshing the formula in sheet `tmp_currentPrice`
 */
function refreshUDF() {
  // Get the sheet that contains the user-defined formula (UDF)
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("tmp_currentPrice");

  // Get the range of cells that contain the UDF. Here is column C
  const range = sheet.getRange("$C$2:$C");

  // Retrieve the formulas of all cells in range
  const formulas = range.getFormulas();

  // Clear the content of all cells in range
  range.clearContent();
  SpreadsheetApp.flush();

  // then refresh the UDF in all cells in range
  range.setFormulas(formulas);
  SpreadsheetApp.flush();
}
```
```javascript
function createTimeDrivenTriggers() {
  let weekDays = [
    ScriptApp.WeekDay.MONDAY,
    ScriptApp.WeekDay.TUESDAY,
    ScriptApp.WeekDay.WEDNESDAY,
    ScriptApp.WeekDay.THURSDAY,
    ScriptApp.WeekDay.FRIDAY
    ];
  let weekEnd = [
    ScriptApp.WeekDay.SATURDAY,
    ScriptApp.WeekDay.SUNDAY
  ]

  for (var i=0; i<weekDays.length; i++) {
    // Trigger the refreshUDF() function every weekday at 17:00 timezone Saigon.
    ScriptApp.newTrigger('refreshUDF')
      .timeBased()
      .onWeekDay(weekDays[i])
      .atHour(17)
      .everyWeeks(1)
      .inTimezone('Asia/Saigon')
      .create();
  }
}
```

**Comment by thinh-vu** [comment]
Hi @andrey-jef 
Cám ơn bạn đã chia sẻ code Google Apps Scripts, code này sẽ có lợi nếu bạn nào quan tâm và chọn phương pháp mình quen thuộc.
---
Mình mới bổ sung khả năng xuất dữ liệu của vnstock từ Google Colab sang Google Sheets dễ dàng với file demo mới, trong mục cuối cùng có tên Data Export. Bạn có thể tìm thấy cập nhật này ở nhánh `beta` nhé. Link file demo: [tại đây](https://github.com/thinh-vu/vnstock/blob/beta/demo/gen2_vnstock_demo_index_all_functions_testing_2023.ipynb)
