### ISSUE TITLE
"financial_report" not working.

### ISSUE THREAD

**Issue by TriDangKhoa** [thinh-vu/vnstock#114]
It seem like "financial_report" code could not run smoothy. Please kindly review.

Thanks,
Regards,

**Comment by thinh-vu** [comment]
Chào bạn,
Lỗi này đã được cập nhật và sửa lỗi trong bản beta và giờ được chính thức phát hành qua bản v0.2.8.9. Bạn có thể tham khảo tại đây https://docs.vnstock.site/changes_log/#15-2-2024
Chúc bạn thành công!
