### ISSUE TITLE
VNindex không hiển thị trước 2020

### ISSUE THREAD

**Issue by hhc2tech** [thinh-vu/vnstock#117]
**Mô tả lỗi**
Code xuất dữ liệu VNindex

from vnstock import * #import all functions

#df = stock_historical_data(symbol='VNINDEX', start_date='2001-01-01', end_date='2023-10-10', resolution='1D', type='index')
df = stock_historical_data(symbol='VNINDEX', start_date= "2001-01-01", end_date= TODAY, resolution='1D', type='index')
fig = candlestick_chart(df,
                  title='VNINDEX Candlestick Chart with MA and Volume', x_label='Date', y_label='Price', ma_periods=[50,200],
                  show_volume=True, figure_size=(15, 8), reference_period=300,
                  colors=('lightgray', 'gray'), reference_colors=('black', 'blue'))
fig.show()

**Kết quả**
chỉ xuất được dữ liệu sau 2020

![image](https://github.com/thinh-vu/vnstock/assets/25620467/e778ffc8-33ee-489d-82f6-5f6664368779)
<img width="687" alt="vnindex" src="https://github.com/thinh-vu/vnstock/assets/25620467/fcb6ff0e-3182-43f7-9af4-2d375b4c7917">

**Comment by kunwang2000** [comment]
đổi nguồn thành TCBS đó ông
df = stock_historical_data(symbol='VNINDEX', start_date= "2001-01-01", end_date= TODAY, resolution='1D', type='index', **source ='TCBS'**)

**Comment by thinh-vu** [comment]
Cám ơn @kunwang2000 đã hỗ trợ bạn @hhc2tech.
Mình đóng ticket này nhé.
