### ISSUE TITLE
Hàm `fund_details` vẫn hiển thị kết quả khi tên mã quỹ bị gõ thiếu

### ISSUE THREAD

**Issue by sonpro1296** [thinh-vu/vnstock#118]
**Cách tái hiện lại lỗi để xử lý**
Các bước để tái hiện sự cố:

1. Sử dụng hàm `fund_details(symbol='VESA', type='nav_report')`
2. Vẫn hiển thị ra thông tin của quỹ VESAF

**Mong muốn đạt được**
Hàm trả về lỗi, hoặc thông báo chưa có thông tin quỹ nếu mã quỹ nhập vào không đúng

**Ảnh chụp màn hình**
<img width="558" alt="Screenshot 2024-03-14 at 16 26 49" src="https://github.com/thinh-vu/vnstock/assets/17319142/f975c73a-cac1-429f-ba6f-88d14ea1a629">
**Máy tính để bàn (vui lòng cung cấp thông tin sau):**
 - Hệ điều hành: Ubuntu 22.04
 - Phiên bản: 0.2.8.9

P/S: Mình có thể contribute vào code thông qua việc sửa lỗi này được không ạ?

**Comment by thinh-vu** [comment]
Chào @sonpro1296 
Cám ơn bạn đã chia sẻ ý kiến. 
Hàm này mình thiết kế cho phép tìm kiếm một quỹ theo tên được nhập vào, API tự động gửi thông tin tìm kiếm và trả về tên quỹ phù hợp. Trong trường hợp bạn chia sẻ không rõ là VESAF có đúng với ý bạn đang tìm kiếm chưa nhỉ? Thực tế thì nếu người dùng muốn giới hạn chính xác kết quả trả về chỉ cần nhập chính xác tên quỹ vì số lượng quỹ không nhiều nên khó trùng lặp.
Bạn có thể đóng góp code theo ý tưởng của mình và gửi Pull Request nhé, mình sẽ trao đổi thêm để cập nhật nếu phù hợp.
Cám ơn bạn!

**Comment by sonpro1296** [comment]
Ý của mình là khi sử dụng hàm với từ khóa 'VESA', hàm nên trả về lỗi / warning vì không tìm được mã quỹ phù hợp
Mình nghĩ nên có một cơ chế self-defense của bản thân thư viện trong trường hợp này:
- Nên bắt buộc user nhập đúng mã quỹ/ thông báo nếu nhập sai, không nên quá phụ thuộc vào kết quả API trả về (mình hoàn toàn không kiểm soát được kết quả nếu nhập sai)
- Số lượng quỹ không nhiều trong hiện tại nhưng hoàn toàn có thể tăng lên trong tương lai
- Mã quỹ có thể thay đổi trong tương lai, khi đó rất có khả năng kết quả trả về sẽ thay đổi, khi đó những script chạy tự động có thể không biết về thay đổi này, dẫn đến kết quả sai lệch

**Comment by thinh-vu** [comment]
Hi @sonpro1296 
Cám ơn bạn đã làm rõ hơn về hướng đề xuất.
Hiện tại mình đang phát triển và nâng cấp bản vnstock thế hệ 3 nên tạm thời sẽ không sửa ngay các lỗi này mà sẽ hoàn thiện khi nâng cấp cùng lúc với bản vnstock mới.
Thông tin về dự án vnstock-next bạn có thể tham khảo [tại đây](https://github.com/vnstock-hq/vnstock-next).

**Comment by thinh-vu** [comment]
Vnstock3 đã hỗ trợ thông tin quỹ mở. Hàm đã được thêm cơ chế kiểm tra, yêu cầu nhập đầy đủ tên khi tra cứu dữ liệu.
Bạn có thể xem thêm chi tiết [tại đây](https://vnstocks.com/docs/huong-dan/du-lieu-quy-mo)
