### ISSUE TITLE
`financial_ratio_compare` trả về "Excel file format cannot be determined, you must specify an engine manually."

### ISSUE THREAD

**Issue by HMDank** [thinh-vu/vnstock#120]
**Mô tả lỗi**
Hàm financial_ratio_compare không hoạt động. Dữ liệu trả về không phải định dạng Excel

**Cách tái hiện lại lỗi để xử lý**
Các bước để tái hiện sự cố:
1. Sử dụng VSCode
2. Sử dụng hàm 'financial_ratio_compare'
3. Thực thi lệnh financial_ratio_compare(symbol_ls=["CTG", "TCB", "ACB"], industry_comparison=True, frequency='Yearly', start_year=2022) như trên docs.
4. Gặp lỗi "Excel file format cannot be determined, you must specify an engine manually" giống financial_ratio trước đây.

**Mong muốn đạt được**
Fix lỗi như ver 0.2.8.8

**Ảnh chụp màn hình**
![image](https://github.com/thinh-vu/vnstock/assets/109755535/c5b20052-98d7-4d1b-bb3c-d2fdefaa5823)

**Máy tính để bàn (vui lòng cung cấp thông tin sau):**
 - Hệ điều hành: Win 11

**Comment by thinh-vu** [comment]
Cám ơn @HMDank đã gửi phản hồi
Mình sẽ kiểm tra và trao đổi thêm với bạn về lỗi này nhé.

**Comment by thinh-vu** [comment]
Hi @HMDank 
Xin lỗi bạn vì đã để bạn đợi lâu. Mình bị bỏ sót ticket này. 
Lỗi mà bạn gặp phải do API không thể truy cập do SSI bật chế độ chặn truy cập từ bot bằng dịch vụ CloudFlare.
Hiện tại các API liên quan đến SSI không thể dùng được và mình đã loại bỏ khi nâng cấp bản vnstock3.
Chúc bạn trải nghiệm mới mẻ với phiên bản vnstock3 nhé.
