### ISSUE TITLE
Error in API response

### ISSUE THREAD

**Issue by tuanphongpham** [thinh-vu/vnstock#121]
Hi Thinh,
Thank you for creating handy VNstock!
I a, coping with below error when working with vnstock. Could you please have a look at it when you have a chance.

I am running this command : 
financial_report (symbol='FPT', report_type='IncomeStatement', frequency='Yearly', periods=15, latest_year=None)

and always cope with below error:

Error in API response <!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Blocked - SSI</title>
<style>body{background-color:#fff;color:#000;font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.5;margin:0}.container{margin:50px auto;max-width:600px;padding:0 24px;text-align:center}small{font-size:14px}</style>

</head>
<body>
<div class="container">
<svg xmlns="http://www.w3.org/2000/svg" width="200px" height="84px" viewBox="0 0 2202.96 1993.62">
<defs>
<style>.cls-1{fill:#e22127;stroke:#fff;stroke-miterlimit:10;stroke-width:5px}.cls-2{fill:#fff}</style>
</defs>
<title>logo</title>
<g id="Layer_2" data-name="Layer 2">
<g id="Layer_1-2" data-name="Layer 1">
<path class="cls-1" d="M2200.46 1991.12H2.5V2.5h2197.96v1988.62z" />
<path class="cls-2" d="M1014.29 1271.05c58 34.42 154.77 87 263.49 88.5h4.47c61.4 0 105.22-16.69 133.65-43 29.07-26.93 40.37-62.36 40.75-94.79-1.12-111.4-118.05-163.17-223.58-222.15C1125.74 940.73 1028 878.24 1028 767.55l.09-3.24c1.89-142.8 127.43-214.66 294.37-214.74h2.91c94.11.95 192.21 25.46 230.45 33.81l2.51.54v-35.55l-1.55-.38c-41.59-9.26-137.24-32.21-231-33.23l-6.63-.06c-85.62 0-164.53 16.92-224.29 55C1033.49 608.48 993.6 680.07 993 763.84v1.6c0 136 116.31 205.84 223.2 264.61 108.1 58.22 205.77 109.93 205.5 187.61l-.19 3.65c-2.29 49.46-28.39 102.89-143.13 103.43-106.55-1-207.78-60.06-261.73-92.91l-.64-.39-1.68 1.69v37.92z" />
<path class="cls-2" d="M1328 601.69h.13c89.64.92 181.24 33.51 230 49.57h.15v-27.53c-51-16.86-139.23-45.26-229.83-46.33h-5.14c-62.31 0-121.11 11.21-165 40h.06c-45.09 29.19-76.7 78.2-77 141 .37 115.6 116.8 172.35 222.93 231.69 107.7 58.81 205.92 118.64 205.7 218.2v3.22c-2 100.36-77.35 176.63-231.47 176.79h-1.24c-109.12-1-219.55-50-261.26-70l-1.74-.87v29.3l.62.33c50.39 23.21 154.15 64.16 262.29 65.49h6.5c79.21 0 142.85-15.93 187.75-50.14 46.2-35.12 71.34-90.83 71.75-150.55v-.71c-.13-126.36-116.19-191-222.8-250-107.86-58.66-206-113.7-205.77-198.92v-3.44C1116 655 1207.3 601.76 1328 601.69z" />
<path class="cls-2" d="M1408.84 921.17c-108.2-57.58-206.67-106.71-206-164.07l.18-3.56c1.42-63.54 47.78-88.92 120.64-89.79 84.08.76 171 39.22 231.85 63.6l.87.39 1.92-1.93V691l-1.15-.43C1497.49 666.49 1412.46 630.2 1324 629h-2.85c-39.61 0-76.48 8.29-105 28.12-29.35 20.19-48.15 53.69-48.24 96 2.85 96.15 118.75 138.61 223.79 198.51 106.68 59.14 204.91 127.5 204.87 246.91v3.17c-2.23 151.58-124.76 238.52-317 238.73h-2.94c-109.62-1.17-225.93-37.87-260.61-47l-1.8-.53v36l.62.15c40.79 11.36 152.88 44.88 261.36 46.06l8.08.05c97.85 0 182.43-20.78 244.51-63.73 63.7-43.83 102.1-122.32 102.81-209.36v-2.26c-.06-142.54-115.75-219.4-222.83-278.61zM313.68 1271.05c57.88 34.42 154.77 87 263.43 88.5h4.46c61.41 0 105.26-16.69 133.65-43 29.08-26.93 40.38-62.36 40.79-94.79-1.15-111.4-118-163.17-223.58-222.15-107.36-58.88-205.12-121.37-205-232.06v-3.24c2-142.8 127.39-214.66 294.34-214.74h3.06c94.05.95 192.18 25.46 230.36 33.81l2.51.54v-35.55l-1.55-.38c-41.56-9.26-137.25-32.21-230.92-33.23l-6.69-.06c-85.56 0-164.52 16.92-224.22 55C332.88 608.48 293 680.07 292.35 763.84v1.6c0 136 116.31 205.84 223.14 264.61 108.17 58.22 205.8 109.93 205.43 187.61l-.15 3.65c-2.27 49.46-28.31 102.89-143.13 103.43-106.5-1-207.69-60.06-261.64-92.91l-.65-.39-1.67 1.69v37.92z" />
<path class="cls-2" d="M627.34 601.69h.22c89.49.92 181.24 33.51 230 49.57h.1v-27.53c-51-16.86-139.17-45.26-229.77-46.33h-5.17c-62.31 0-121.15 11.21-164.9 40-45.09 29.19-76.7 78.2-77.1 141 .46 115.6 116.89 172.35 223 231.69 107.61 58.83 205.71 118.66 205.65 218.22v3.22c-2 100.36-77.38 176.63-231.53 176.79h-1.24c-109.07-1-219.49-50-261.2-70l-1.77-.87v29.3l.59.33c50.38 23.21 154.12 64.16 262.28 65.49h6.6c79.18 0 142.75-15.93 187.72-50.14 46.14-35.12 71.34-90.83 71.74-150.55v-.71c-.12-126.36-116.18-191-222.76-250-107.87-58.64-206.07-113.68-205.8-198.9v-3.44c1.3-103.79 92.59-157.07 213.3-157.14z" />
<path class="cls-2" d="M708.16 921.17C600 863.59 501.49 814.46 502.24 757.1l.06-3.56c1.48-63.54 47.87-88.92 120.7-89.79 84 .76 171 39.22 231.88 63.6l.81.39 2-1.93V691l-1.27-.43C796.88 666.49 711.78 630.2 623.38 629h-2.92c-39.57 0-76.39 8.29-104.94 28.12-29.36 20.19-48 53.69-48.28 96C470.12 849.21 586 891.67 691 951.57c106.77 59.14 205 127.5 204.9 246.91v3.17c-2.17 151.58-124.61 238.52-316.87 238.73h-3c-109.5-1.17-225.93-37.87-260.61-47l-1.74-.53v36l.5.15c40.81 11.36 153 44.88 261.48 46.06l8 .05c98 0 182.48-20.78 244.54-63.73C892 1367.57 930.29 1289.08 931 1202v-2.26c-.06-142.54-115.66-219.4-222.83-278.61zm1097.94 544.59h31.62V528.6h-31.62v937.16zm-72.71-935.21c9.39 197.36.41 901.05 0 934l1.27 1.31h34.5v-937.2h-33.79l-1.95 1.89zm177.1 0c-9.38 197.36-.28 901.05.12 934l-1.33 1.31h-34.4v-937.2h33.75l1.86 1.89z" />
</g>
</g>
</svg>
**<h1>Sorry, your access has been denied</h1>
<p> You are unable to access this website. Try to disable VPN or switch to other networks (4G/5G/Wifi)</p>
<p> Please contact us if the problem persists. </p>
<p> <small><strong>IP :</strong> 106.71.31.17</small> </p>
<p> <small><strong>Ray ID:</strong> 87980ad05c1129c5</small> </p>**
</div>
<script defer integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw==" data-cf-beacon='{"rayId":"7ceba5f071aec75a","version":"2023.4.0","b":1,"token":"55616b0c29c54933afb037e2684c1082","si":100}' crossorigin="anonymous">!function(){var e={343:function(e){"use strict";for(var t=[],n=0;n<256;++n)t[n]=(n+256).toString(16).substr(1);e.exports=function(e,n){var r=n||0,i=t;return[i[e[r++]],i[e[r++]],i[e[r++]],i[e[r++]],"-",i[e[r++]],i[e[r++]],"-",i[e[r++]],i[e[r++]],"-",i[e[r++]],i[e[r++]],"-",i[e[r++]],i[e[r++]],i[e[r++]],i[e[r++]],i[e[r++]],i[e[r++]]].join("")}},944:function(e){"use strict";var t="undefined"!=typeof crypto&&crypto.getRandomValues&&crypto.getRandomValues.bind(crypto)||"undefined"!=typeof msCrypto&&"function"==typeof window.msCrypto.getRandomValues&&msCrypto.getRandomValues.bind(msCrypto);if(t){var n=new Uint8Array(16);e.exports=function(){return t(n),n}}else{var r=new Array(16);e.exports=function(){for(var e,t=0;t<16;t++)0==(3&t)&&(e=4294967296*Math.random()),r[t]=e>>>((3&t)<<3)&255;return r}}},508:function(e,t,n){"use strict";var r=n(944),i=n(343);e.exports=function(e,t,n){var o=t&&n||0;"string"==typeof e&&(t="binary"===e?new Array(16):null,e=null);var a=(e=e||{}).random||(e.rng||r)();if(a[6]=15&a[6]|64,a[8]=63&a[8]|128,t)for(var c=0;c<16;++c)t[o+c]=a[c];return t||i(a)}},168:function(e,t,n){"use strict";var r=this&&this.__assign||function(){return r=Object.assign||function(e){for(var t,n=1,r=arguments.length;n<r;n++)for(var i in t=arguments[n])Object.prototype.hasOwnProperty.call(t,i)&&(e[i]=t[i]);return e},r.apply(this,arguments)};t.__esModule=!0;var i=n(699),o=n(752),a=n(104),c=n(508);!function(){function e(e){var t="";if(t=window.location.origin?window.location.origin:"".concat(window.location.protocol,"://").concat(window.location.host),e&&"string"==typeof e)if(0===e.indexOf("/"))t+=e;else try{var n=new URL(e);return"".concat(n.protocol,"://").concat(n.host).concat(n.pathname)}catch(e){}else{var r=window.location.pathname;r&&r.length>0&&(t+=r)}return t}function t(e){return null==e?void 0:Math.round(1e3*e)/1e3}function n(e,t){for(var n in e){var r=e[n];void 0!==t&&("number"==typeof r||"string"==typeof r?t[n]=r:Array.isArray(r)&&(t[n]=JSON.parse(JSON.stringify(r))))}}!function(){var u,s,f=window.performance||window.webkitPerformance||window.msPerformance||window.mozPerformance,d="data-cf-beacon",l=document.currentScript||("function"==typeof document.querySelector?document.querySelector("script[".concat(d,"]")):void 0),v=c(),p=[],m=window.__cfBeacon?window.__cfBeacon:{};if(!m||"single"!==m.load){if(l){var g=l.getAttribute(d);if(g)try{m=r(r({},m),JSON.parse(g))}catch(e){}else{var y=l.getAttribute("src");if(y&&"function"==typeof URLSearchParams){var h=new URLSearchParams(y.replace(/^[^\?]+\??/,"")),T=h.get("token");T&&(m.token=T);var w=h.get("spa");m.spa=null===w||"true"===w}}m&&"multi"!==m.load&&(m.load="single"),window.__cfBeacon=m}if(f&&m&&m.token){var S,b=!1;document.addEventListener("visibilitychange",(function(){if("hidden"===document.visibilityState){if(L&&A()){var t=e();(null==S?void 0:S.url)==t&&(null==S?void 0:S.triggered)||P(),x(t)}!b&&S&&(b=!0,R())}else"visible"===document.visibilityState&&(new Date).getTime()}));var E={};"function"==typeof PerformanceObserver&&((0,a.onLCP)(O),(0,a.onFID)(O),(0,a.onFCP)(O),(0,a.onINP)(O),(0,a.onTTFB)(O),PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.includes("layout-shift")&&(0,a.onCLS)(O));var L=m&&(void 0===m.spa||!0===m.spa),C=m.send&&m.send.to?m.send.to:void 0===m.version?"https://cloudflareinsights.com/cdn-cgi/rum":null,P=function(r){var a=function(e,t){c.resources=e,0!=t&&(c.bypassTiming=!0),m&&(1===m.r&&(c.resources=[]),(0,o.sendObjectBeacon)("",c,(function(){}),!1,C),void 0!==m.forward&&void 0!==m.forward.url&&(0,o.sendObjectBeacon)("",c,(function(){}),!1,m.forward.url))},c=function(r){var o,a,c,s=f.timing,d=f.memory,l=r||e(),g={memory:{},timings:{},resources:[],tempResources:[],referrer:(a=document.referrer||"",c=p[p.length-1],L&&S&&c?c.url:a),eventType:i.EventType.Load,firstPaint:0,firstContentfulPaint:0,startTime:k(),versions:{fl:m?m.version:"",js:"2023.4.2",timings:1},pageloadId:v,location:l,wd:M(),b:m.b};if(null==u){if("function"==typeof f.getEntriesByType){var y=f.getEntriesByType("navigation");y&&Array.isArray(y)&&y.length>0&&(g.timingsV2={},g.versions.timings=2,delete g.timings,n(y[0],g.timingsV2))}1===g.versions.timings&&n(s,g.timings),n(d,g.memory)}else _(g);if(g.firstPaint=F("first-paint"),g.firstContentfulPaint=F("first-contentful-paint"),m&&(m.icTag&&(g.icTag=m.icTag),g.siteToken=m.token),"function"==typeof f.getEntriesByType){var h=null!==(o=f.getEntriesByType("resource"))&&void 0!==o?o:[],T=0,w=0;h.forEach((function(e){var n={n:e.name,s:t(e.startTime),d:t(e.duration),i:e.initiatorType,p:e.nextHopProtocol,rs:t(e.redirectStart),re:t(e.redirectEnd),fs:t(e.fetchStart),ds:t(e.domainLookupStart),de:t(e.domainLookupEnd),cs:t(e.connectStart),ce:t(e.connectEnd),qs:t(e.requestStart),ps:t(e.responseStart),pe:t(e.responseEnd),ws:t(e.workerStart),ss:t(e.secureConnectionStart),ts:e.transferSize,ec:e.encodedBodySize,dc:e.decodedBodySize};g.tempResources&&void 0===g.tempResources[w]&&(g.tempResources[w]=[]);var r=JSON.stringify(n).length;T+r<62e3&&g.tempResources?(T+=r,g.tempResources[w].push(n)):(w++,T=0)}))}return JSON.stringify(g).length>=64e3&&(g.resources=[]),void 0!==u&&(delete g.timings,delete g.memory),g}(r);if(c&&m){var s=c.tempResources;if(delete c.tempResources,L&&s&&0===s.length&&a([],0),!s)return;s.forEach((function(e,t){a(e,t)}))}},R=function(){var t=function(){var t=f.getEntriesByType("navigation")[0],n="";try{n="function"==typeof f.getEntriesByType?new URL(null==t?void 0:t.name).pathname:s?new URL(s).pathname:window.location.pathname}catch(e){}var r={referrer:document.referrer||"",eventType:i.EventType.WebVitalsV2,versions:{js:"2023.4.2"},pageloadId:v,location:e(),landingPath:n,startTime:k(),wd:M(),b:m.b};return m&&(m.version&&(r.versions.fl=m.version),m.icTag&&(r.icTag=m.icTag),r.siteToken=m.token),E&&["lcp","fid","cls","fcp","ttfb","inp"].forEach((function(e){r[e]={value:-1,path:void 0},E[e]&&void 0!==E[e].value&&(r[e]=E[e])})),_(r),r}();L||(t.resources=[],delete t.tempResources),m&&(0,o.sendObjectBeacon)("",t,(function(){}),!0,C)},B=function(){var t=window.__cfRl&&window.__cfRl.done||window.__cfQR&&window.__cfQR.done;t?t.then(P):P(),S={id:v,url:e(),ts:(new Date).getTime(),triggered:!0}};"complete"===window.document.readyState?B():window.addEventListener("load",(function(){window.setTimeout(B)}));var A=function(){return L&&0===p.filter((function(e){return e.id===v})).length},x=function(e){p.push({id:v,url:e,ts:(new Date).getTime()}),p.length>3&&p.shift()};L&&(s=e(),function(t){var n=t.pushState;if(n){var r=function(){v=c(),"function"==typeof f.clearResourceTimings&&f.clearResourceTimings()};t.pushState=function(i,o,a){u=e(a);var c=e(),s=!0;return u==c&&(s=!1),s&&(A()&&((null==S?void 0:S.url)==c&&(null==S?void 0:S.triggered)||P(c),x(c)),r()),n.apply(t,[i,o,a])},window.addEventListener("popstate",(function(t){A()&&((null==S?void 0:S.url)==u&&(null==S?void 0:S.triggered)||P(u),x(u)),u=e(),r()}))}}(window.history))}}function O(e){var t,n,r,i,o,a,c,u=window.location.pathname;switch("INP"!==e.name&&(E[e.name.toLowerCase()]={value:e.value,path:u}),e.name){case"CLS":(c=e.attribution)&&E.cls&&(E.cls.element=c.largestShiftTarget,E.cls.currentRect=null===(t=c.largestShiftSource)||void 0===t?void 0:t.currentRect,E.cls.previousRect=null===(n=c.largestShiftSource)||void 0===n?void 0:n.previousRect);break;case"FID":(c=e.attribution)&&E.fid&&(E.fid.element=c.eventTarget,E.fid.name=c.eventType);break;case"LCP":(c=e.attribution)&&E.lcp&&(E.lcp.element=c.element,E.lcp.size=null===(r=c.lcpEntry)||void 0===r?void 0:r.size,E.lcp.url=c.url,E.lcp.rld=c.resourceLoadDelay,E.lcp.rlt=c.resourceLoadTime,E.lcp.erd=c.elementRenderDelay,E.lcp.it=null===(i=c.lcpResourceEntry)||void 0===i?void 0:i.initiatorType,E.lcp.fp=null===(a=null===(o=c.lcpEntry)||void 0===o?void 0:o.element)||void 0===a?void 0:a.getAttribute("fetchpriority"));break;case"INP":(null==E.inp||Number(E.inp.value)<Number(e.value))&&(E.inp={value:Number(e.value),path:u},(c=e.attribution)&&E.inp&&(E.inp.element=c.eventTarget,E.inp.name=c.eventType))}}function k(){return f.timeOrigin}function M(){return navigator.webdriver}function _(e){if("function"==typeof f.getEntriesByType){var t=f.getEntriesByType("navigation"),r={};e.timingsV2={},t&&t[0]&&t[0].nextHopProtocol&&(r.nextHopProtocol=t[0].nextHopProtocol),n(r,e.timingsV2)}}function F(e){var t;if("first-contentful-paint"===e&&E.fcp&&E.fcp.value)return E.fcp.value;if("function"==typeof f.getEntriesByType){var n=null===(t=f.getEntriesByType("paint"))||void 0===t?void 0:t.filter((function(t){return t.name===e}))[0];return n?n.startTime:0}return 0}}()}()},752:function(e,t){"use strict";t.__esModule=!0,t.sendObjectBeacon=void 0,t.sendObjectBeacon=function(e,t,n,r,i){void 0===r&&(r=!1),void 0===i&&(i=null);var o=i||(t.siteToken&&t.versions.fl?"/cdn-cgi/rum?".concat(e):"/cdn-cgi/beacon/performance?".concat(e)),a=!0;if(navigator&&"string"==typeof navigator.userAgent)try{var c=navigator.userAgent.match(/Chrome\/([0-9]+)/);c&&c[0].toLowerCase().indexOf("chrome")>-1&&parseInt(c[1])<81&&(a=!1)}catch(e){}if(navigator&&"function"==typeof navigator.sendBeacon&&a&&r){t.st=1;var u=JSON.stringify(t);navigator.sendBeacon(o,new Blob([u],{type:"application/json"}))}else{t.st=2,u=JSON.stringify(t);var s=new XMLHttpRequest;n&&(s.onreadystatechange=function(){4==this.readyState&&204==this.status&&n()}),s.open("POST",o,!0),s.setRequestHeader("content-type","application/json"),s.send(u)}}},699:function(e,t){"use strict";var n,r;t.__esModule=!0,t.FetchPriority=t.EventType=void 0,(r=t.EventType||(t.EventType={}))[r.Load=1]="Load",r[r.Additional=2]="Additional",r[r.WebVitalsV2=3]="WebVitalsV2",(n=t.FetchPriority||(t.FetchPriority={})).High="high",n.Low="low",n.Auto="auto"},104:function(e,t){!function(e){"use strict";var t,n,r,i,o,a=function(){return window.performance&&performance.getEntriesByType&&performance.getEntriesByType("navigation")[0]},c=function(e){if("loading"===document.readyState)return"loading";var t=a();if(t){if(e<t.domInteractive)return"loading";if(0===t.domContentLoadedEventStart||e<t.domContentLoadedEventStart)return"dom-interactive";if(0===t.domComplete||e<t.domComplete)return"dom-content-loaded"}return"complete"},u=function(e){var t=e.nodeName;return 1===e.nodeType?t.toLowerCase():t.toUpperCase().replace(/^#/,"")},s=function(e,t){var n="";try{for(;e&&9!==e.nodeType;){var r=e,i=r.id?"#"+r.id:u(r)+(r.className&&r.className.length?"."+r.className.replace(/\s+/g,"."):"");if(n.length+i.length>(t||100)-1)return n||i;if(n=n?i+">"+n:i,r.id)break;e=r.parentNode}}catch(e){}return n},f=-1,d=function(){return f},l=function(e){addEventListener("pageshow",(function(t){t.persisted&&(f=t.timeStamp,e(t))}),!0)},v=function(){var e=a();return e&&e.activationStart||0},p=function(e,t){var n=a(),r="navigate";return d()>=0?r="back-forward-cache":n&&(r=document.prerendering||v()>0?"prerender":document.wasDiscarded?"restore":n.type.replace(/_/g,"-")),{name:e,value:void 0===t?-1:t,rating:"good",delta:0,entries:[],id:"v3-".concat(Date.now(),"-").concat(Math.floor(8999999999999*Math.random())+1e12),navigationType:r}},m=function(e,t,n){try{if(PerformanceObserver.supportedEntryTypes.includes(e)){var r=new PerformanceObserver((function(e){Promise.resolve().then((function(){t(e.getEntries())}))}));return r.observe(Object.assign({type:e,buffered:!0},n||{})),r}}catch(e){}},g=function(e,t,n,r){var i,o;return function(a){t.value>=0&&(a||r)&&((o=t.value-(i||0))||void 0===i)&&(i=t.value,t.delta=o,t.rating=function(e,t){return e>t[1]?"poor":e>t[0]?"needs-improvement":"good"}(t.value,n),e(t))}},y=function(e){requestAnimationFrame((function(){return requestAnimationFrame((function(){return e()}))}))},h=function(e){var t=function(t){"pagehide"!==t.type&&"hidden"!==document.visibilityState||e(t)};addEventListener("visibilitychange",t,!0),addEventListener("pagehide",t,!0)},T=function(e){var t=!1;return function(n){t||(e(n),t=!0)}},w=-1,S=function(){return"hidden"!==document.visibilityState||document.prerendering?1/0:0},b=function(e){"hidden"===document.visibilityState&&w>-1&&(w="visibilitychange"===e.type?e.timeStamp:0,L())},E=function(){addEventListener("visibilitychange",b,!0),addEventListener("prerenderingchange",b,!0)},L=function(){removeEventListener("visibilitychange",b,!0),removeEventListener("prerenderingchange",b,!0)},C=function(){return w<0&&(w=S(),E(),l((function(){setTimeout((function(){w=S(),E()}),0)}))),{get firstHiddenTime(){return w}}},P=function(e){document.prerendering?addEventListener("prerenderingchange",(function(){return e()}),!0):e()},R=function(e,t){t=t||{},P((function(){var n,r=[1800,3e3],i=C(),o=p("FCP"),a=m("paint",(function(e){e.forEach((function(e){"first-contentful-paint"===e.name&&(a.disconnect(),e.startTime<i.firstHiddenTime&&(o.value=Math.max(e.startTime-v(),0),o.entries.push(e),n(!0)))}))}));a&&(n=g(e,o,r,t.reportAllChanges),l((function(i){o=p("FCP"),n=g(e,o,r,t.reportAllChanges),y((function(){o.value=performance.now()-i.timeStamp,n(!0)}))})))}))},B={passive:!0,capture:!0},A=new Date,x=function(e,i){t||(t=i,n=e,r=new Date,M(removeEventListener),O())},O=function(){if(n>=0&&n<r-A){var e={entryType:"first-input",name:t.type,target:t.target,cancelable:t.cancelable,startTime:t.timeStamp,processingStart:t.timeStamp+n};i.forEach((function(t){t(e)})),i=[]}},k=function(e){if(e.cancelable){var t=(e.timeStamp>1e12?new Date:performance.now())-e.timeStamp;"pointerdown"==e.type?function(e,t){var n=function(){x(e,t),i()},r=function(){i()},i=function(){removeEventListener("pointerup",n,B),removeEventListener("pointercancel",r,B)};addEventListener("pointerup",n,B),addEventListener("pointercancel",r,B)}(t,e):x(t,e)}},M=function(e){["mousedown","keydown","touchstart","pointerdown"].forEach((function(t){return e(t,k,B)}))},_=function(e,r){r=r||{},P((function(){var o,a=[100,300],c=C(),u=p("FID"),s=function(e){e.startTime<c.firstHiddenTime&&(u.value=e.processingStart-e.startTime,u.entries.push(e),o(!0))},f=function(e){e.forEach(s)},d=m("first-input",f);o=g(e,u,a,r.reportAllChanges),d&&h(T((function(){f(d.takeRecords()),d.disconnect()}))),d&&l((function(){var c;u=p("FID"),o=g(e,u,a,r.reportAllChanges),i=[],n=-1,t=null,M(addEventListener),c=s,i.push(c),O()}))}))},F=0,I=1/0,N=0,D=function(e){e.forEach((function(e){e.interactionId&&(I=Math.min(I,e.interactionId),N=Math.max(N,e.interactionId),F=N?(N-I)/7+1:0)}))},V=function(){return o?F:performance.interactionCount||0},j=function(){"interactionCount"in performance||o||(o=m("event",D,{type:"event",buffered:!0,durationThreshold:0}))},q=0,H=function(){return V()-q},J=[],U={},z=function(e){var t=J[J.length-1],n=U[e.interactionId];if(n||J.length<10||e.duration>t.latency){if(n)n.entries.push(e),n.latency=Math.max(n.latency,e.duration);else{var r={id:e.interactionId,latency:e.duration,entries:[e]};U[r.id]=r,J.push(r)}J.sort((function(e,t){return t.latency-e.latency})),J.splice(10).forEach((function(e){delete U[e.id]}))}},W={},Q=function e(t){document.prerendering?P((function(){return e(t)})):"complete"!==document.readyState?addEventListener("load",(function(){return e(t)}),!0):setTimeout(t,0)},X=function(e,t){t=t||{};var n=[800,1800],r=p("TTFB"),i=g(e,r,n,t.reportAllChanges);Q((function(){var o=a();if(o){var c=o.responseStart;if(c<=0||c>performance.now())return;r.value=Math.max(c-v(),0),r.entries=[o],i(!0),l((function(){r=p("TTFB",0),(i=g(e,r,n,t.reportAllChanges))(!0)}))}}))};e.onCLS=function(e,t){!function(e,t){t=t||{},R(T((function(){var n,r=[.1,.25],i=p("CLS",0),o=0,a=[],c=function(e){e.forEach((function(e){if(!e.hadRecentInput){var t=a[0],n=a[a.length-1];o&&e.startTime-n.startTime<1e3&&e.startTime-t.startTime<5e3?(o+=e.value,a.push(e)):(o=e.value,a=[e])}})),o>i.value&&(i.value=o,i.entries=a,n())},u=m("layout-shift",c);u&&(n=g(e,i,r,t.reportAllChanges),h((function(){c(u.takeRecords()),n(!0)})),l((function(){o=0,i=p("CLS",0),n=g(e,i,r,t.reportAllChanges),y((function(){return n()}))})),setTimeout(n,0))})))}((function(t){!function(e){if(e.entries.length){var t=e.entries.reduce((function(e,t){return e&&e.value>t.value?e:t}));if(t&&t.sources&&t.sources.length){var n=(r=t.sources).find((function(e){return e.node&&1===e.node.nodeType}))||r[0];if(n)return void(e.attribution={largestShiftTarget:s(n.node),largestShiftTime:t.startTime,largestShiftValue:t.value,largestShiftSource:n,largestShiftEntry:t,loadState:c(t.startTime)})}}var r;e.attribution={}}(t),e(t)}),t)},e.onFCP=function(e,t){R((function(t){!function(e){if(e.entries.length){var t=a(),n=e.entries[e.entries.length-1];if(t){var r=t.activationStart||0,i=Math.max(0,t.responseStart-r);return void(e.attribution={timeToFirstByte:i,firstByteToFCP:e.value-i,loadState:c(e.entries[0].startTime),navigationEntry:t,fcpEntry:n})}}e.attribution={timeToFirstByte:0,firstByteToFCP:e.value,loadState:c(d())}}(t),e(t)}),t)},e.onFID=function(e,t){_((function(t){!function(e){var t=e.entries[0];e.attribution={eventTarget:s(t.target),eventType:t.name,eventTime:t.startTime,eventEntry:t,loadState:c(t.startTime)}}(t),e(t)}),t)},e.onINP=function(e,t){!function(e,t){t=t||{},P((function(){var n=[200,500];j();var r,i=p("INP"),o=function(e){e.forEach((function(e){e.interactionId&&z(e),"first-input"===e.entryType&&!J.some((function(t){return t.entries.some((function(t){return e.duration===t.duration&&e.startTime===t.startTime}))}))&&z(e)}));var t,n=(t=Math.min(J.length-1,Math.floor(H()/50)),J[t]);n&&n.latency!==i.value&&(i.value=n.latency,i.entries=n.entries,r())},a=m("event",o,{durationThreshold:t.durationThreshold||40});r=g(e,i,n,t.reportAllChanges),a&&(a.observe({type:"first-input",buffered:!0}),h((function(){o(a.takeRecords()),i.value<0&&H()>0&&(i.value=0,i.entries=[]),r(!0)})),l((function(){J=[],q=V(),i=p("INP"),r=g(e,i,n,t.reportAllChanges)})))}))}((function(t){!function(e){if(e.entries.length){var t=e.entries.sort((function(e,t){return t.duration-e.duration||t.processingEnd-t.processingStart-(e.processingEnd-e.processingStart)}))[0];e.attribution={eventTarget:s(t.target),eventType:t.name,eventTime:t.startTime,eventEntry:t,loadState:c(t.startTime)}}else e.attribution={}}(t),e(t)}),t)},e.onLCP=function(e,t){!function(e,t){t=t||{},P((function(){var n,r=[2500,4e3],i=C(),o=p("LCP"),a=function(e){var t=e[e.length-1];if(t){var r=Math.max(t.startTime-v(),0);r<i.firstHiddenTime&&(o.value=r,o.entries=[t],n())}},c=m("largest-contentful-paint",a);if(c){n=g(e,o,r,t.reportAllChanges);var u=T((function(){W[o.id]||(a(c.takeRecords()),c.disconnect(),W[o.id]=!0,n(!0))}));["keydown","click"].forEach((function(e){addEventListener(e,u,!0)})),h(u),l((function(i){o=p("LCP"),n=g(e,o,r,t.reportAllChanges),y((function(){o.value=performance.now()-i.timeStamp,W[o.id]=!0,n(!0)}))}))}}))}((function(t){!function(e){if(e.entries.length){var t=a();if(t){var n=t.activationStart||0,r=e.entries[e.entries.length-1],i=r.url&&performance.getEntriesByType("resource").filter((function(e){return e.name===r.url}))[0],o=Math.max(0,t.responseStart-n),c=Math.max(o,i?(i.requestStart||i.startTime)-n:0),u=Math.max(c,i?i.responseEnd-n:0),f=Math.max(u,r?r.startTime-n:0),d={element:s(r.element),timeToFirstByte:o,resourceLoadDelay:c-o,resourceLoadTime:u-c,elementRenderDelay:f-u,navigationEntry:t,lcpEntry:r};return r.url&&(d.url=r.url),i&&(d.lcpResourceEntry=i),void(e.attribution=d)}}e.attribution={timeToFirstByte:0,resourceLoadDelay:0,resourceLoadTime:0,elementRenderDelay:e.value}}(t),e(t)}),t)},e.onTTFB=function(e,t){X((function(t){!function(e){if(e.entries.length){var t=e.entries[0],n=t.activationStart||0,r=Math.max(t.domainLookupStart-n,0),i=Math.max(t.connectStart-n,0),o=Math.max(t.requestStart-n,0);e.attribution={waitingTime:r,dnsTime:i-r,connectionTime:o-i,requestTime:e.value-o,navigationEntry:t}}else e.attribution={waitingTime:0,dnsTime:0,connectionTime:0,requestTime:0}}(t),e(t)}),t)},Object.defineProperty(e,"__esModule",{value:!0})}(t)}},t={};!function n(r){var i=t[r];if(void 0!==i)return i.exports;var o=t[r]={exports:{}};return e[r].call(o.exports,o,o.exports,n),o.exports}(168)}();</script>
</body>
</html>

**Comment by thinh-vu** [comment]
Chào bạn,
Cám ơn bạn đã báo lỗi chương trình.
Lỗi bạn cung cấp đã được ghi nhận trong tháng 4 thường xuyên. Lý do là bởi phía SSI đang chặn các truy cập qua API mà hệ thống "dự đoán" không phải con người thực hiện (bot/crawler). Thông tin thêm với bạn, các công ty chứng khoán lớn hiện đang rầm rộ triển khai kết nối hệ thống KRX nên các biện pháp kỹ thuật và bảo mật được siết chặt. Bạn không cần phải làm gì thêm ngoài việc đổi nguồn dữ liệu phân tích sang các hàm có nguồn từ TCBS.
Chúc bạn thành công!

**Comment by tuanphongpham** [comment]
Cam on Thinh nhieu nha. :)
