### ISSUE TITLE
Hàm finance.income_statement và finance.ratio không nhận tham số symbol

### ISSUE THREAD

**Issue by nhh1501** [thinh-vu/vnstock#125]
**Mô tả lỗi**
Gọi hàm finance.income_statement và finance.ratio với tham số symbol không hoạt động
Lỗi trả về khi gọi hàm income_statement với symbol
{TypeError}TypeError("Finance.income_statement() got an unexpected keyword argument 'symbol'")

**Cách tái hiện lại lỗi để xử lý**
Các bước để tái hiện sự cố:
1. Sử dụng VSCode
2. Sử dụng hàm 'finance.income_statement' và 'finance.ratio'
3. Thực thi lệnh 'stock.finance.income_statement(symbol = 'HPG' ,period='quarter', lang='en')'
4. Gặp lỗi '{TypeError}TypeError("Finance.income_statement() got an unexpected keyword argument 'symbol'")'

**Comment by thinh-vu** [comment]
Chào bạn, 
Trong vnstock3, để truy xuất thông tin BCTC cho 1 mã CP cụ thể, bạn cần cung cấp mã symbol khi khởi tạo đối tượng chứ không phải khi gọi hàm income_statement, vv
Dưới đây là cú pháp gọi hàm chuẩn:
```
from vnstock3 import Vnstock
stock = Vnstock().stock(symbol='VCI', source='VCI')
stock.finance.income_statement(period='year', lang='vi')
```
Bạn cập nhật lại cách gọi hàm và tham khảo thêm hướng dẫn chi tiết trên website nhé: https://vnstocks.com/docs/huong-dan/bao-cao-tai-chinh

**Comment by nhh1501** [comment]
Cảm ơn bạn. Mình có đọc nguồn tham khảo trên website thì mình thấy có thể
sử dụng thêm tham số symbol để thay đổi nhanh mà không cần phải khởi tạo
một stock mới

**Comment by thinh-vu** [comment]
Cám ơn bạn đã thông tin thêm, mình quên mất vụ này. Okay, để mình kiểm tra rồi sửa lại nhé.

**Comment by thinh-vu** [comment]
Mình đã khắc phục lỗi này từ phiên bản 0.3.0.5. Mình đóng ticket này tại đây.
