### ISSUE TITLE
Giá cổ phiếu trả về trong quá khứ không chính xác

### ISSUE THREAD

**Issue by hainguyen-namiq** [thinh-vu/vnstock#129]
Chào anh Thịnh, hôm nay em có đang ngồi tính toán lại các chỉ số P/B, P/E vì em nghĩ báo cáo chỉ số trả về có vẻ không chính xác, nên em có tính toán lại.
Thì em có phát hiện ra giá trị lịch sử của cố phiếu HPG có sự khác biệt so với trên fireant.
![Screenshot from 2024-06-11 00-23-15](https://github.com/thinh-vu/vnstock/assets/85979082/69bee7f3-d2c9-4600-86ed-6d2266ebf355)
![Screenshot from 2024-06-11 00-25-04](https://github.com/thinh-vu/vnstock/assets/85979082/238ced4f-1b76-4dd9-834e-7cacb46a9ce0)

Mong anh thông cảm cho sự không chỉn chu của em trong việc đặt câu hỏi.

**Comment by thinh-vu** [comment]
Chào @hainguyen-namiq 
Sự sai khác mà em chỉ ra là đúng bởi em đang sử dụng 2 dữ liệu khác nhau để so sánh. Dữ liệu giá lịch sử mà Vnstock cung cấp là dữ liệu sử dụng cho việc biểu diễn đồ thị kỹ thuật (giá đã điều chỉnh) và anh có nêu rõ trong mô tả dữ liệu. Giá mà em đang sử dụng làm tham chiếu là giá trị giao dịch thực tế của cổ phiếu (chưa điều chỉnh). Cả 2 dữ liệu này đều đúng, chỉ là mục đích em cần sử dụng là gì để dùng nguồn dữ liệu phù hợp. 
![image](https://github.com/thinh-vu/vnstock/assets/39723360/87291445-fb65-47fa-8de9-6eef505b7df7)

**Comment by hainguyen-namiq** [comment]
Dạ vâng em cảm ơn, em nắm được vấn đề rồi ạ. Hiện tại thì em đang cố gắng tìm các chỉ số cở bản P/B, P/E phán ánh được đúng công ty ở thời điểm quá khứ. Anh có insight về các báo cáo hiện tại. Anh cho em hỏi có cách nào mà em có thể tìm được các chỉ số đó không?. Nếu anh có bận quá anh có thể gợi ý hoặc chỉ cho em biết là em phải tính nó ở đâu được không ạ
Em cảm ơn anh nhiều.

**Comment by thinh-vu** [comment]
Hi @hainguyen-namiq Hiện tại mục chỉ số tài chính trên website phân tích của công ty chứng khoán cũng có các chỉ số này cho nhiều năm và vnstock3 cung cấp đầy đủ. https://vnstocks.com/docs/huong-dan/bao-cao-tai-chinh#ch%E1%BB%89-s%E1%BB%91-t%C3%A0i-ch%C3%ADnh
Không rõ ý em về việc các chỉ số trong quá khứ mà em nói đến có khác gì với các chỉ số được công bố ở đây?
