### ISSUE TITLE
Cash FLow khi không có kết quả trả về bị lỗi

### ISSUE THREAD

**Issue by yellow1912** [thinh-vu/vnstock#133]
Đây là lỗi nếu tìm cách lấy Cash Flow của một symbol không có thông tin này (vnstock3 bản mới nhất)
`Unexpected error occurred while fetching Cash Flow: "None of [Index(['ticker', 'yearReport', 'lengthReport'], dtype='object')] are in the [columns]"`

Theo mình thì nên đưa về 1 empty result thì đúng hơn.

**Comment by thinh-vu** [comment]
Hi @yellow1912 
Cám ơn bạn đã báo lỗi, 
Bạn cho mình xin chi tiết 1 số mã mà bạn bắt gặp lỗi nhé. Việc này giúp mình kiểm tra và sửa lỗi đơn giản hơn thay vì ngồi test để tìm ra đâu là mã không có thông tin Cash Flow như bạn mô tả.

**Comment by yellow1912** [comment]
Bạn có thể lấy subsidiaries của ACM
company = Vnstock().stock(symbol='ACM', source='TCBS').company
subsidiaries = company.subsidiaries()
print(subsidiaries)

**Comment by thinh-vu** [comment]
Đã bổ sung cơ chế báo lỗi trong trường hợp request không tồn tại dữ liệu. Cập nhật áp dụng từ phiên bản 3.0.8
