### ISSUE TITLE
Flatten nested columns

### ISSUE THREAD

**Issue by yellow1912** [thinh-vu/vnstock#134]
Với vnstock3, một số reports ví dụ như ratio có dạng columns nested (ví dụ như Meta, ở dưới Meta lại có yearReport)

Để tiện thao tác, theo ý mình là nên flatten hết tất cả columns, từ đó ví dụ như cần index hay gì đó cũng đơn giản hơn rất nhiều.

**Comment by thinh-vu** [comment]
Chào @yellow1912 
Cám ơn bạn đã đóng góp ý kiến.
Mục đích thiết kế DataFrame sử dụng multi-level index cho phép tách các bộ chỉ số theo nhóm 1 cách dễ dàng. Nếu bạn không quen hoặc cảm thấy bất tiện với việc sử dụng multi-level index thì có thể loại bỏ phân cấp này với 1 câu lệnh. Việc này được thực hiện dễ dàng thay vì flatten ngay từ đầu vì sẽ không thể tái tạo phân cấp một cách dễ dàng như vậy từ phía người dùng.
Bản thân mình cũng cần dạng multi-level index này để dễ dàng chọn các bộ chỉ số theo nhóm và đối chiếu.
Bạn có thể tham khảo đoạn code mẫu này nhé.

```
ratio_df = stock.finance.ratio(period='year', lang='vi').head()
ratio_df.columns = ratio_df.columns.droplevel()
```
![image](https://github.com/thinh-vu/vnstock/assets/39723360/eb21b7a2-96c2-461e-8048-98c220fb7ce5)
