### ISSUE TITLE
API lấy data từ VCI trả về các kết quả khác nhau trên colab và local machine

### ISSUE THREAD

**Issue by huuhung7301** [thinh-vu/vnstock#135]
**Mô tả lỗi**
<img width="500" alt="Screenshot 2024-07-16 at 2 41 46 pm" src="https://github.com/user-attachments/assets/5a1731f1-f14f-4798-a548-62caa0a1553e">

<img width="539" alt="Screenshot 2024-07-16 at 2 42 46 pm" src="https://github.com/user-attachments/assets/e03daa32-9579-49b0-ad4a-25e43abfaec2">

Khi dùng trên colab, mình luôn có thể lấy data từ thời gian thực. Còn khi dùng trên máy mình, đôi khi mình có thể lấy data từ thời gian thực với end_date = hôm nay, đôi khi không và phải +1 ngày vào end_date. Hiện mình chưa tìm ra nguyên nhân, mà thế này bắt code hơi bất tiện. Không biết b có giải pháp gì như thay đổi khung thời gian không.

**Comment by huuhung7301** [comment]
À thêm nữa thì có lúc mình uninstall api package và install lại thì mình có thể lấy data theo thời gian thực.

**Comment by thinh-vu** [comment]
Cám ơn @huuhung7301 đã báo lỗi
Mình sẽ kiểm tra và câp nhật logic tính toán trong bản tới nhé.

**Comment by thinh-vu** [comment]
Lỗi xảy ra khi bạn chạy trên Colab và máy cục bộ bởi múi giờ hệ thống khác nhau. Trên Colab giờ UTC nên chậm hơn giờ hệ thống 7 tiếng, do đó sẽ có những khoảng thời gian khi ngày của thời gian UTC đang chậm hơn so với ngày của giờ VN 1 ngày. Phần này mình sẽ sửa lại logic code để xử lý sai lệch này nhé.
