### ISSUE TITLE
Thiếu thư viện sau khi cài vnstock3

### ISSUE THREAD

**Issue by sonpro1296** [thinh-vu/vnstock#136]
**Mô tả lỗi**
Cài đặt vnstock3 xong nhưng khi chạy hàm `income_statement()` thì trả về lỗi thiếu module `seaborn`

**Cách tái hiện lại lỗi để xử lý**
Các bước để tái hiện sự cố:
1. Tạo project mới, venv mới
2. Cài đặt vnstock3 qua pip
3. Chạy file như dưới qua venv
`from vnstock3 import Finance

acb = Finance('ACB', 'year', source='TCBS')

print(acb.income_statement())
`

**Mong muốn đạt được**
Không gặp lỗi thiếu thư viện sau khi cài nữa

**Máy tính để bàn (vui lòng cung cấp thông tin sau):**
 - Hệ điều hành: Ubuntu
 - Phiên bản: vnstock3 0.3.0.6

**Comment by thinh-vu** [comment]
Cám ơn @sonpro1296 đã báo lỗi,
Mình có gặp lỗi này 1 lần mà note lại xong quên. Để mình bổ sung seaborn vào requirement khi cài đặt thư viện là xong.
