### ISSUE TITLE
Bổ sung type hint cho các functions 

### ISSUE THREAD

**Issue by sonpro1296** [thinh-vu/vnstock#137]
Mình thấy việc thêm type hint cho các hàm sẽ có 1 vài tác dụng
- Tận dụng được các tính năng hỗ trợ của ide (autocomplete, copilot,...)
- Tích hợp thêm với các formatting tool để đảm bảo code quality của thư viện

**Comment by thinh-vu** [comment]
Cám ơn bạn @sonpro1296 đã gợi ý. Mình sẽ dần hoàn thiện phần type hint trong các lần nâng cấp vnstock theo thời gian nhé.
