### ISSUE TITLE
Dữ liệu về finance của một cổ phiếu chỉ lấy được từ năm 2013

### ISSUE THREAD

**Issue by hainguyen-namiq** [thinh-vu/vnstock#138]
**Mô tả lỗi**
Khi lấy dữ liệu finance của một cổ phiếu, hầu như là tất cả data đều bị chặn ở ngưỡng từ năm 2013, không thể nào lấy được data ở thời điểm trước đó nữa.
Có vẻ như tất cả các có phiếu nếu đều bị như vậy

**Comment by thinh-vu** [comment]
Chào bạn @hainguyen-namiq 
Dữ liệu báo cáo tài chính theo nguồn VCI có giới hạn 10 năm tức mốc cũ nhất là năm 2013. Nếu bạn có nhu cầu truy xuất dữ liệu xa hơn, có thể chuyển sang nguồn TCBS nhé.
Chúc bạn thành công!
