### ISSUE TITLE
Intraday Function.

### ISSUE THREAD

**Issue by TriDangKhoa** [thinh-vu/vnstock#14]
Hi Anh,

Function Intraday is not working and the errors notice as below:

121         data = requests.get('https://apipubaws.tcbs.com.vn/stock-insight/v1/intraday/{}/his/paging?page={}&size={}'.format(symbol, page_num, page_size)).json()
--> 122     df = json_normalize(data['data']).rename(columns={'p':'price', 'v':'volume', 't': 'time'})

Hope you could spend your valuable time to review and fix this errors. I try but could not fix this problem. :(

Many thanks and best regards,

**Comment by thinh-vu** [comment]
Thanks Khoa for reporting it. I will review and fix it soon.

**Comment by thinh-vu** [comment]
You can find the fix for this issue in the beta version. Get updates by installing the package from the beta branch. For more information, check the REAME file in the beta version and this discussion thread https://github.com/thinh-vu/vnstock/discussions/16#discussioncomment-5953323.

**Comment by happylinhdn** [comment]
Hi anh @thinh-vu 
Why not bring this fix to https://pypi.org/project/vnstock/
I saw the version on PYPI is still 0.1.4

**Comment by thinh-vu** [comment]
Thank you, @happylinhdn, for raising this concern. We can now proceed with the update since no recent issues have been found in the beta version. This will assist us in stabilizing the version on Pypi.
