### ISSUE TITLE
Lỗi lấy dữ liệu theo ngày trên phiên bản python 3.12

### ISSUE THREAD

**Issue by trucphan66** [thinh-vu/vnstock#140]
**Mô tả lỗi**
Mô tả một cách rõ ràng và ngắn gọn về lỗi.

def fetch_stock_history(stock_symbol, start_date, end_date):
    try:
        # Create a Vnstock instance
             # Get the stock object for the given symbol
              # Fetch historical data using the 'history' method with start and end dates
        data_list = stock.quote.history(symbol=stock_symbol, start=start_date, end=end_date, interval='1d'),
         # Return data as a DataFrame
        return data_list

**Mong muốn đạt được**
lấy được giá đóng cửa của toàn cổ phiếu theo thời gian cụ thể

**Ảnh chụp màn hình**
<img width="737" alt="Bug stock quote history" src="https://github.com/user-attachments/assets/457f5346-ac48-4a62-811d-bd7ad4e54b3c">

**Máy tính để bàn (vui lòng cung cấp thông tin sau):**
 - Hệ điều hành: [ví dụ: Windows]
 - Phiên bản: Python 3.12. 
 - PyCharm 2024.1.4 (Professional Edition)
 - Windows 11.0

**Comment by thinh-vu** [comment]
Chào @trucphan66 
Theo như log màn hình của bạn thì bạn chưa định nghĩa biến stock trước khi chạy câu lệnh của mình. 

```
from vnstock3 import Vnstock
stock = Vnstock().stock(symbol='VCI', source='VCI')
```
Bạn có thể xem đầy đủ hướng  dẫn tại đây: https://vnstocks.com/docs/huong-dan/thong-ke-gia-lich-su

**Comment by trucphan66** [comment]
Hi Thinh Vu,
Lệnh mình như sau:
import vnstock3
stock_price = vnstock3.Quote('VNM',source='VCI').history(start='2019-01-01',end='2023-12-31').head()
print(stock_price)
Mình đã khắc phục được lỗi, cám ơn bạn.
Tuy nhiên, Mong muốn là lấy được giá lịch sử của toàn bộ mã chứng khoán trên sàn trong thời gian cụ thể. Mong bạn tư vấn.

**Comment by thinh-vu** [comment]
Chúc mừng bạn đã khắc phục được lỗi. Để lấy thông tin nhiều mã cổ phiếu cùng luac bạn có thể tìm hiểu cách dùng vòng lặp for, while cơ bản. Bạn có thể tham gia gói thành viên để ủng hộ dự án và sử dụng tính năng cập nhật thông tin thị trường cho rổ cổ phiếu bạn chọn bằng chương trình plugin chuyên nghiệp.
Thông tin chi tiết gói thành viên tại đây: https://vnstocks.com/docs/insiders-program/gioi-thieu-chuong-trinh-vnstock-insiders-program

Chúc bạn sử dụng Vnstock hiệu quả!
