### ISSUE TITLE
Warning khi lấy dữ liệu công ty

### ISSUE THREAD

**Issue by yellow1912** [thinh-vu/vnstock#141]
**Mô tả lỗi**
2024-08-02 23:35:15,133 - vnstock3.common.data.data_explorer - WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
/usr/local/lib/python3.10/dist-packages/vnstock3/explorer/tcbs/company.py:271: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  df['event_desc'] = df['event_desc'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())
  
Đây là cảnh báo xảy ra khi lấy dữ liệu về sự kiện công ty.

**Comment by thinh-vu** [comment]
Cám ơn @yellow1912 đã báo lỗi. Mình ko rõ lỗi này xảy ra với trường hợp cụ thể nào nên tạm thời mình bổ sung cơ chế try/except khi parse HTML content cho trường thông tin event_desc như bạn mô tả nhé. Thay đổi sẽ được cập nhật khi ra mắt bản tiếp theo v3.0.7
