### ISSUE TITLE
Bid/Ask data

### ISSUE THREAD

**Issue by havinhnam** [thinh-vu/vnstock#146]
Hi,
Do you have Bid/Ask data for 20 years Vietnam stock data.
If the data is EOD data, I need more detail about Buy Up_Sell Down volume and values.
But data is for each Bid/Ask, I can caculate to sum EOD for BuyUP_SellDown volume and values.
Thanks!

**Comment by thinh-vu** [comment]
Chào bạn, 
Cám ơn bạn đã quan  tâm đặt  câu hỏi. 
Trước tiên mình nhờ bạn giúp làm rõ hơn định nghĩa và mẫu dữ liệu tham chiếu về loại  dữ liệu bạn đang nói đến nếu có công khai ví dụ cafeF hoặc từ cty chứng khoán bất kỳ để trao đổi được  chính xác.
Hiện tại chỉ có dữ liệu OHLCV dùng để biểu diễn đồ thị kỹ thuật là có thể truy xuất từ năm 2000 ở 1 số nguồn. Các loại dữ liệu giao dịch khác thường chỉ cung cấp theo ngày giao dịch. Bạn sẽ cần tham khảo các nguồn dữ liệu trả phí chính thức nếu muốn  có dữ liệu lịch sử dài như vậy.
Thân,
