### ISSUE TITLE
lỗi khi gọi lịch sử giá

### ISSUE THREAD

**Issue by DieuKayz** [thinh-vu/vnstock#147]
sử dụng hàm Vnstock().stock.quote.history gặp lỗi

**Cách tái hiện lại lỗi để xử lý**
Môi trường: VS Code ver. 1.92
Code:
    hist = Vnstock().stock(symbol = 'VCI, source = 'VCI').quote.history(start = '2013-01-01', end = '2013-01-02')

>>Traceback (most recent call last):
  File "c:\Users\dinhk\OneDrive\Desktop\SSI thực tập\Midcap\main.py", line 13, in <module>
    hist = Vnstock().stock(symbol = 'VCI', source = 'VCI').quote.history(start = '2013-01-01', end = '2013-01-02')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\vnstock3\common\data\data_explorer.py", line 118, in history
    return self.data_source.history(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\vnstock3\explorer\vci\quote.py", line 100, in history
    df = self._as_df(history_data=json_data[0], asset_type=self.asset_type, interval=ticker.interval)
                                  ~~~~~~~~~^^^
IndexError: list index out of range


Hệ điều hành: Windows 11 Home 23H2, Microsoft Surface Pro X

**Comment by thinh-vu** [comment]
Cám ơn @DieuKayz đã báo lỗi. Mình sẽ kiểm tra và sửa lỗi trong phiên bản tiếp theo.

**Comment by thinh-vu** [comment]
Lỗi đã được khắc phục trong phiên bản 3.0.8. Báo lỗi khi không có dữ liệu hợp lệ trả về, trong trường hợp này khung thời gian truy xuất dữ liệu cho mã VCI không hợp lệ vì VCI giao dịch lần đầu tiên vào 07/07/2017 do đó không có dữ liệu từ 2013.
