### ISSUE TITLE
Không thể xác nhận license trên Vscode

### ISSUE THREAD

**Issue by trungtransg** [thinh-vu/vnstock#149]
Mình có cài đặt và chạy import nhưng chỉ báo lỗi mà không hiển thị xác nhận Đồng ý.

Xin admin cho cách để accept license trên vscode, using notebook.

Nếu ad có thể luôn cái xác nhận license luôn thì tuyệt vời.

cảm ơn.

**Comment by thinh-vu** [comment]
Chào @trungtransg 
Cám ơn bạn đã báo lỗi, bạn giúp mình cung cấp thêm thông tin về hệ điều hành, phiên bản vscode và báo lỗi trên màn hình nếu có để mình tiện hỗ trợ nhé.
Cám ơn bạn

**Comment by trungtransg** [comment]
Xin chào admin,

Mình bổ sung thông tin lỗi xác minh license:

An exception has occurred, use %tb to see the full traceback.

SystemExit: Bạn cần chấp thuận điều khoản, điều kiện để sử dụng Vnstock!

![Screen Shot 2024-10-13 at 10 44 29](https://github.com/user-attachments/assets/49de952c-d144-4e4c-b8d7-df293e9c31cf)

Visual Studio Code: 1.87.1, Python: 3.11.0, OS: Mac

Mình chạy thử trên Jupyter Notebook cũng gặp lỗi, nhưng chạy trên Colab Google thì OK.

Mình có thử add biến vào os nhưng vẫn bị lỗi.

Xin cảm ơn.

**Comment by thinh-vu** [comment]
Hi @trungtransg, 
bạn có thể chat giúp mình qua messenger để mình tiện trao đổi nhanh nhé, bên này nhiều khi mình ko để ý
https://m.me/mr.thinh.ueh
