### ISSUE TITLE
financial_report báo lỗi JSONDecode

### ISSUE THREAD

**Issue by pgiaphu** [thinh-vu/vnstock#2]
em lấy báo cáo tài chính thì báo lỗi như sau:
vnstock.financial_report(symbol='SSI', report_type='BalanceSheet', frequency='Quarterly')

![image](https://user-images.githubusercontent.com/99589333/213910853-76ef533c-d5a6-407d-867f-85ce3c3bc194.png)

**Comment by thinh-vu** [comment]
Cám ơn @pgiaphu đã báo lỗi. Anh đã sửa lỗi trên phát sinh do nâng cấp đoạn code từ phiên bản cũ sang mới. Em có thể cài đặt vnstock từ github source code và chạy lại nhé (package trên pypi chưa được cập nhật).
<img width="713" alt="financial_report_bug_fixed" src="https://user-images.githubusercontent.com/39723360/214757390-2e83efbe-41b1-44bf-9d7d-653557369e83.png">
