### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by LongPML** [thinh-vu/vnstock#20]
Hi, I am new to the packages and currently try to use but I get this error because of HTTP. I had tried on my PC and Colab with a different version (0.1.3 and 0.1.4) and still get the same error. Could you help me with this!

Thanks in advance

![image](https://github.com/thinh-vu/vnstock/assets/59755436/2a9a5257-29ac-49d4-aad6-3db5b6b02409)

**Comment by thinh-vu** [comment]
Chào @LongPML
Bạn có thể chạy lại hàm này như sau `listing_companies (mode='', file='vn_stock_listing_companies_2022-05-20.csv')`. Mình sẽ cập nhật thay đổi vào branch beta. Mặc định hàm này sẽ đọc file csv đính kèm từ Github, khi mode='live' thì đọc dữ liệu từ API.
