### ISSUE TITLE
Add Vnstock command line

### ISSUE THREAD

**Issue by nguyenthang338** [thinh-vu/vnstock#25]
hi @thinh-vu 
Bạn có thể thêm module command line cho app vnstock , thì sẽ dễ sử dụng hơn 
Ví dụ như: 
vnstock list -a       Show toan bộ công ty 
vnstock price -s HPG ,   -> show gia của HPG 

Rồi bổ sung thêm dần dần :)))

**Comment by thinh-vu** [comment]
Chào @nguyenthang338
Cám ơn bạn đã góp ý, mình sẽ ghi nhận để tham khảo thêm. Hiện tại mình chưa thấy đây là critical idea vì mình thiết kế vnstock phục vụ cho mục đích cao nhất là có thể thực hiện các project python hoàn chỉnh chạy theo lịch trình xác định và thực hiện các tác vụ (ví dụ filter cổ phiếu, cập nhật tin sự kiện quyền, cảnh báo, đọc chart pattern, vv). Mình không quá rành command line nên chỉ hiểu rằng nếu mình test project theo từng bước một để truy xuất dữ liệu thì nên dùng Jupyter Notebook để ít nhất có thể lưu lại lệnh và review cũng như render các chart/visual dễ dàng vì command line rất hạn chế. Hiện tại mình khuyến khích các bạn sử dụng python và jupyter notebook cho vnstock để đạt hiệu quả tốt nhất. Mình cung cấp hẳn một notebook có sẵn các hàm để các bạn test, chỉ việc click run để chạy và tùy chỉnh lại tham số nếu cần. Sẽ dễ dàng hơn cho việc kiểm tra theo document lẫn khi mình debug. Bạn có thể tìm thấy nó ở đây nhé https://github.com/thinh-vu/vnstock/blob/main/vnstock_demo_index_all_functions_testing_2023_06_07.ipynb.
Thân!
