### ISSUE TITLE
khá nhiều function hoạt động khi chạy không cho ra kết quả nhu document readme.md 

### ISSUE THREAD

**Issue by nguyenthang338** [thinh-vu/vnstock#26]
@thinh-vu 
ví dụ như hàm , 

pip install vnstock 
from vnstock import *
df =  stock_historical_data(symbol='VNM', 
                            start_date="2021-01-01", 
                            end_date='2022-02-25')
print(df.head())

result , 
[2 rows x 50 columns]
       Open      High       Low     Close   Volume TradingDate
0   98565.0   98655.0   97936.0   98206.0  2299600  2021-01-04
1   98654.0  101556.0   98292.0  100468.0  4013900  2021-01-05
2  100649.0  100921.0   99561.0   99561.0  2823100  2021-01-06
3   99742.0  100468.0   99561.0  100105.0  2453000  2021-01-07
4  101103.0  102372.0  100559.0  101556.0  3323000  2021-01-08

Khi mình lấy cái quả , nó chỉ hiện 5  kết quả ra thôi :))) 
Mình là dev  ,mà khi cài lib . để sử dụng mà cug thấy khá khoai:)) ). Vẫn mất thời gian mò vào lib

**Comment by thinh-vu** [comment]
Chào @nguyenthang338,
Khi bạn chạy thư viện trong command prompt và chọng print(df.head()) thực chất chỉ là để xem trước dữ liệu. Kể cả bạn print (df) nó cũng chỉ hiển thị 10 dòng dù là jupyter notebook hay command prompt/terminal. Tuy nhiên, thực chất biến df đã được gán dữ liệu và lưu trong bộ nhớ. Để bạn có thể truy xuất toàn bộ dữ liệu cho mục đích xem trước thì xuất file ra csv hoặc excel là đơn giản nhất thay vì xem trong giao diện CLI. Nếu bạn quen với việc dùng CLI thì thực ra chỉ cần subset dataframe ví dụ print(df[:20]) để xem trước 20 dòng hoặc di chuyển xa hơn số dòng. Tuy nhiên nó vẫn bị hạn chế với kiểu xem này nếu Dataframe có quá nhiều column. Do đó khuyến khích bạn sử dụng excel để xem trước dữ liệu thay vì CLI khi có nhiều data. Đây là những kiến thức về pandas căn bản, bạn có thể tham khảo thêm vì mình ko chắc bạn có dev python hay quen với việc xử lý dữ liệu thường xuyên không. 
Hy vọng câu trả lời này có thể giúp bạn nắm được cách sử dụng vnstock.
Thân

**Comment by nguyenthang338** [comment]
hi @thinh-vu,
Cảm ơn bạn nhiều ,
