### ISSUE TITLE
Lỗi thiếu module requests

### ISSUE THREAD

**Issue by happylinhdn** [thinh-vu/vnstock#29]
Chào anh Thịnh,
Đối với 1 số máy windows, sau khi cài python mới nhất, cài vnstock. thực hiện hàm ticker_overview sẽ báo lỗi thiếu module requests. Cách fix tạm là pip install requests
Nhờ team thêm requirements để khi cài đặt vnstock thì có cài theo module liên quan luôn nhé anh

**Comment by thinh-vu** [comment]
Chào @happylinhdn 
Cám ơn em đã phản hồi, anh sẽ thêm các module cần thiết vào project.toml cho bản cập nhật tiếp theo nhé. Lỗi này xuất hiện khi mình cài bản python thuần hoặc từ Windows Store vì nó sẽ không cài kèm theo các thư viện thông dụng. Khi chạy vnstock với môi trường Google Colab hoặc Anaconda sẽ không gặp lỗi.
