### ISSUE TITLE
the unit on price

### ISSUE THREAD

**Issue by hwypengsir** [thinh-vu/vnstock#39]
When i get price of stock 'CET':
```
df =  stock_historical_data(symbol='CET',start_date="2023-06-30",end_date='2023-07-04')
df
                       time  open  high  low  close  volume
0 2023-06-30 09:00:00+07:00   9.1   9.1  8.6    8.6   13200
1 2023-07-03 09:00:00+07:00   9.0   9.1  8.4    8.5   15400
```
The unit is in 1000 VND or not?

**Comment by thinh-vu** [comment]
Hi @hwypengsir, the default unit is 1000 VND. You can always validate the unit and the price (or any data provided by vnstock) by checking the price table on any security company's website, such as SSI or TCBS.
Thanks
