### ISSUE TITLE
Function price_board trả số liệu sai

### ISSUE THREAD

**Issue by caubechankiu** [thinh-vu/vnstock#41]
Fuction price_board đang gọi đến api "https://apipubaws.tcbs.com.vn/stock-insight/v1/stock/second-tc-price?tickers=MWG"
Ngay lúc này api này trả về kết quả
`
{
    "data": [
        {
            "t": "MWG",
            "fv": 1.57,
            "mav": 3.84,
            "nstv": 268600,
            "nstp": 27.0,
            "rsi": 67.9774,
            "macdv": 0.00,
            "macdsignal": "Neutral",
            "tsignal": "Buy",
            "avgsignal": "Strong Buy",
            "ma20": 43002.5,
            "ma50": 40632.0,
            "ma100": 40334.5,
            "session": 1,
            "mw3d": 5.0,
            "mw1m": 8.9,
            "mw3m": 16.4,
            "mw1y": -28.9,
            "rs3d": 93.0,
            "rs1m": 80.0,
            "rs3m": 61.0,
            "rs1y": 9.0,
            "rsavg": 61.0,
            "hp1m": 45500,
            "hp3m": 45500,
            "hp1y": 74100,
            "lp1m": 40650,
            "lp3m": 37700,
            "lp1y": 37700,
            "hp1yp": -38.6,
            "lp1yp": 20.7,
            "pe": 24.9,
            "pb": 2.8,
            "roe": 0.117042,
            "oscore": 3.8,
            "av": 64800,
            "bv": 91200,
            "ev": 47892,
            "hmp": 44000,
            "mscore": 0.68,
            "delta1m": 6.2,
            "delta1y": -27.9,
            "seq": 1688716740,
            "vnid3d": 0.3,
            "vnid1m": 2.7,
            "vnid3m": 6.3,
            "vnid1y": -1.0,
            "cp": 45050.0,
            "vnipe": 13.6522,
            "vnipb": 1.65116
        }
    ]
}
`
Theo như kết quả này giá của cổ phiếu đang là 45050 nhưng giá trên bảng giá của tcbs đang là 45500.
![photo_2023-07-08_17-40-44](https://github.com/thinh-vu/vnstock/assets/15911787/12b2e039-95bf-4061-a54a-5eb7c10f0191)

**Comment by thinh-vu** [comment]
Cám ơn @caubechankiu
Mình sẽ kiểm tra lại nhé, phần này nếu sai thì là do gán volumn name không chính xác vì code name từ TCBS cho các data không rõ ràng, mình dựa vào giá trị nhận được, so sánh và gán tên.

**Comment by caubechankiu** [comment]
> Cám ơn @caubechankiu Mình sẽ kiểm tra lại nhé, phần này nếu sai thì là do gán volumn name không chính xác vì code name từ TCBS cho các data không rõ ràng, mình dựa vào giá trị nhận được, so sánh và gán tên.

Mình không tìm thấy api này được tcbs dùng ở đâu trên website của họ.
Field để lấy giá đang là "cp" nhưng giá trị lại khác so với số liệu trên website bảng giá của tcbs. Còn có 2 field khác có số giống thì là "hp1m" và "hp3m" nhưng mình đoán vẫn không phải. "hp" ở đây là high price có nghĩa là giá cao nhất trong vòng 1 tháng và 3 tháng chứ k phải giá hiện tại

Mình nghĩ có sự sai khác ở đây là do phiên ATC, có thể giá ở api này chỉ là giá ngay lúc trước phiên ATC thôi.

**Comment by vnstock-official** [comment]
@caubechankiu mình mới kiểm tra lại hồi trưa, API này hiện tại TCBS không dùng trên hệ thống front-end của bảng giá nữa nhưng cũng chưa dẹp, thời điểm gần 2 năm trước mình dùng thì nó là API trên website của họ. Function này mình sẽ tìm kiếm giải pháp thay thế hoặc tạm thời tắt trong cập nhật tiếp theo do thông tin chưa được xác thực, dễ gây nhầm lẫn.

**Comment by thinh-vu** [comment]
> @caubechankiu mình mới kiểm tra lại hồi trưa, API này hiện tại TCBS không dùng trên hệ thống front-end của bảng giá nữa nhưng cũng chưa dẹp, thời điểm gần 2 năm trước mình dùng thì nó là API trên website của họ. Function này mình sẽ tìm kiếm giải pháp thay thế hoặc tạm thời tắt trong cập nhật tiếp theo do thông tin chưa được xác thực, dễ gây nhầm lẫn.

Cập nhật lại đoạn này: Thực ra API này vẫn tồn tại nha bạn, trên bảng giá, bạn click chỗ góc phải gần hình bánh răng có nút 1/3, khi click để mở tab thứ 2 thì API này mới xuất hiện trong inspection Network. `cp` là close price (Hiển thị là Giá), giá trị này  có thể thay đổi khi xem real time trong ngày giao dịch bởi thời điểm đó đâu có phải là giá đã chốt.
