### ISSUE TITLE
 Cảm ơn bác vì cái api này vẫn chạy được :>>> 

### ISSUE THREAD

**Issue by huuhung7301** [thinh-vu/vnstock#43]
Dạo trước e vẫn lấy data trên investing.com, nhưng được cái bị chặn liên tục, hqua vô lại thì k vào được :> nay tìm được bác mừng quá. Cảm ơn ạ. Update cho mọi người là vẫn dùng được thôi :>

**Comment by thinh-vu** [comment]
Cám ơn bạn đã chia sẻ. Chúc bạn thành công với dự án của mình cùng vnstock và đừng quên theo dõi repo này để nhận cập nhật mới nhất.
