### ISSUE TITLE
Values of "Cổ phiếu phổ thông" in BalanceData seems to be wrong?

### ISSUE THREAD

**Issue by enderphan94** [thinh-vu/vnstock#5]
As Cổ phiếu phổ thông in year of 2022 in the market is 1.097.026.572. but reported in the BalanceData is "10,970,265,720,000.0".

I'm not sure why there are so many zeros afterwards.

**Comment by thinh-vu** [comment]
Hi Ender,
To get the correct number, you might need to perform a data cleanup step. I’m aware of this issue, but I haven’t taken any further steps to clean it up yet.
