### ISSUE TITLE
Translate vnstock documentation to English, enabling seamless integration with diverse investment analysis platforms in the future.

### ISSUE THREAD

**Issue by thinh-vu** [thinh-vu/vnstock#59]

**Comment by yellow1912** [comment]
Bạn cần giúp phần này không?

**Comment by thinh-vu** [comment]
Chào @yellow1912,
Có nha bạn. Nếu bạn có thể đóng góp phần dịch thì tốt quá.

**Comment by yellow1912** [comment]
okie để mình sẽ bắt đầu, bạn muốn dịch từ đâu trước?

**Comment by thinh-vu** [comment]
@yellow1912 bạn giúp mình bắt đầu từ phần II. nhé. Cám ơn bạn nhiều

**Comment by yellow1912** [comment]
Okie bạn, khi nào xong báo mình

**Comment by thinh-vu** [comment]
@yellow1912 Hiện tại mình đã hoàn thiện nội dung trang docs bằng tiếng Việt. Bạn có thể hỗ trợ việc dịch nếu có thể ha. Tất cả file markdown sẽ được chứa trong thư mục docs tại đây: https://github.com/thinh-vu/vnstock/tree/main/docs/_doc

**Comment by yellow1912** [comment]
Bạn muốn dịch xong để nội dung dịch mới ở chỗ nào?
