### ISSUE TITLE
Báo lỗi cho tính năng

### ISSUE THREAD

**Issue by huuhung7301** [thinh-vu/vnstock#66]
data lấy từ database không cùng đơn vị, có thể là đơn vị nghìn đồng hoặc đồng. Không lọc sạch được data vì có những cổ phiếu lên tới 1 triệu 1 cổ, có cổ chỉ vài trăm đồng. Nếu cổ có giá trị 900 thì k biết được là 900 đồng hay 900 nghìn. cách duy nhất lúc này là loại những cổ có giá trị quá thấp đi thì mới dùng được data.

**Comment by thinh-vu** [comment]
Chào @huuhung7301 
Cám ơn bạn đã phản hồi. Bạn vui lòng giúp mình cung cấp thêm chi tiết lỗi xảy ra với mã nào, cho mình xin screenshot và mô tả cụ thể hơn để mình tiện kiểm tra nhé. Hiện tại thông tin mình nhận được chung chung sẽ rất mất thời gian để hiểu bạn đang nhắc đến lỗi ở phần nào.
