### ISSUE TITLE
Báo lỗi cho tính năng lấy intraday data vào giờ nghỉ (ví dụ giờ trưa)

### ISSUE THREAD

**Issue by yellow1912** [thinh-vu/vnstock#68]
**Mô tả lỗi**
Khi lấy data intraday của 1 symbol bất kỳ ví dụ như VCB vào giờ nghỉ ví dụ như 12h trưa 1 ngày giao dịch bình thường

Lỗi hiện ra là:  unconverted data remains:  12:47:48 (ví dụ)

**Comment by thinh-vu** [comment]
Cám ơn @yellow1912 đã báo lỗi. Mình sẽ để ý fix lỗi này trong bản tới.

**Comment by thinh-vu** [comment]
Đã bổ sung cơ chế kiểm tra trạng thái phản hồi thành công (status_code = 200) trước khi lấy dữ liệu để tránh lỗi.
