### ISSUE TITLE
Dữ liệu data bị trùng

### ISSUE THREAD

**Issue by yellow1912** [thinh-vu/vnstock#76]
**Mô tả lỗi**
Một số trường hợp data dữ liệu trả về bị trùng, ví dụ

![image](https://github.com/thinh-vu/vnstock/assets/374134/8fa70044-fa74-4eb0-9de7-a399d915c91d)

Đây là data của vjc, khi xuất ra csv thì có đến 2 dòng cùng 1 ngày

**Comment by thinh-vu** [comment]
@yellow1912 Chào bạn, bạn chia sẻ cụ thể giúp mình dữ liệu trùng này xuất hiện ở hàm nào, điều kiện bạn gặp lỗi cụ thể hơn nha. Hiện tại với thông tin như này khá mơ hồ, mình không thể xác thực được.

**Comment by yellow1912** [comment]
```
date_format = "%Y-%m-%d"
default_start_date = datetime.strptime('2020-01-01', date_format).date()
end_date = datetime.today().date()
data = stock_historical_data('VJC', default_start_date.strftime(date_format), end_date.strftime(date_format), '1D', 'stock')
boolean = not data["time"].is_unique      # True (credit to @Carsten)
print(data[data.duplicated(['time'], keep=False)])
print(boolean)
quit()
```

![image](https://github.com/thinh-vu/vnstock/assets/374134/4846ff2a-989b-4337-a6f3-c275f3388a94)

Đây nha bạn
