### ISSUE TITLE
Báo lỗi cho tính năng

### ISSUE THREAD

**Issue by Yunkaizdasick** [thinh-vu/vnstock#77]
**Mô tả lỗi**
Mô tả một cách rõ ràng và ngắn gọn về lỗi.

**Cách tái hiện lại lỗi để xử lý**
Các bước để tái hiện sự cố:
1. Sử dụng VSCode '...'
2. Sử dụng hàm 'industry_analysis'
3. Thực thi lệnh 'industry_analysis("VNM", lang='vi')'
4. Gặp lỗi không xuất được DataFrame phân tích ngành

**Mong muốn đạt được**
xuất ra được DataFrame phân tích ngành

**Ảnh chụp màn hình**
![image](https://github.com/thinh-vu/vnstock/assets/137812958/dea4b6a3-6938-4bf3-94d5-99df3a459d63)

**Comment by thinh-vu** [comment]
Hi @Yunkaizdasick 
Cám ơn bạn đã báo lỗi. Sau khi kiểm tra thì mình thấy hàm vẫn hoạt động bình thường. Bạn thử lại giúp mình nha.
![image](https://github.com/thinh-vu/vnstock/assets/39723360/7dbdd30f-0b90-4ddf-9d46-875605a8fc15)
