### ISSUE TITLE
Unit của index không đúng

### ISSUE THREAD

**Issue by yellow1912** [thinh-vu/vnstock#78]
Khi lấy data của index ví dụ VNINDEX thì không nên * 1000.

![image](https://github.com/thinh-vu/vnstock/assets/374134/14f0f4dc-91ad-4a1a-8a57-3e08cb872cb4)

**Comment by thinh-vu** [comment]
Cám ơn @yellow1912 đã phát hiện ra lỗi này. Mình đã sửa trong mã nguồn và sẽ commit lên sớm nha.
