### ISSUE TITLE
FR: crawl data related to mutual funds from https://fmarket.vn/

### ISSUE THREAD

**Issue by andrey-jef** [thinh-vu/vnstock#88]
**Yêu cầu tính năng có liên quan đến một vấn đề? Vui lòng mô tả.**
Cào dữ liệu về quỹ mở (open-ended fund) từ https://fmarket.vn/

**Mô tả giải pháp bạn muốn**
thêm các hàm để truy xuất dữ liệu về quỹ mở

**Mô tả các giải pháp hoặc tính năng thay thế bạn đã xem xét**
N/A

**Bổ sung thông tin**
Status: WIP

**Comment by andrey-jef** [comment]
M có thể góp sức viết docs cho phần này. Nếu được thì nhờ b tạo sẵn file 'mutual_funds.md' rồi chia sẻ để m chỉnh sửa

**Comment by thinh-vu** [comment]
Ok bạn nhé

**Comment by thinh-vu** [comment]
Mình có thêm 1 file `funds.md` cho docs, tuy nhiên mình nghĩ tụi tối ưu và thống nhất code xong đã rồi hãy viết tài liệu để bạn đỡ mất công nha.

**Comment by andrey-jef** [comment]
Status: Finished with features. Waiting for test and integration to main

Related PR: #89 , #99 , #100
