### ISSUE TITLE
Báo lỗi cho tính năng

### ISSUE THREAD

**Issue by NamReplIT** [thinh-vu/vnstock#91]
**Mô tả lỗi**
Số lượng khớp lệnh không đúng với thức tế.

**Cách tái hiện lại lỗi để xử lý**
Các bước để tái hiện sự cố: 
Sử dụng hàm stock_historical_data:
![image](https://github.com/thinh-vu/vnstock/assets/89992703/3f4f94f4-6ffa-47ef-ad1a-e7b25e024edb)

**Mong muốn đạt được**
Số lượng khớp lệnh đúng với thực tế.

**Ảnh chụp màn hình**
![image](https://github.com/thinh-vu/vnstock/assets/89992703/060951df-1e25-4315-862b-82998f56ee1b)

**Máy tính để bàn (vui lòng cung cấp thông tin sau):**

**Bổ sung thông tin**

**Comment by thinh-vu** [comment]
@NamReplIT cho mình hỏi thêm là:
- Thực tế theo ý bạn ở đây là bạn căn cứ vào nguồn dữ liệu nào để làm chuẩn?
- Ticker xảy ra lỗi bạn mô tả là mình SSI hay còn các mã khác?
- Hiện nay, sai khác về dữ liệu này còn tồn tại không bạn? 

theo mình thấy thì bạn đang lấy dữ liệu trong ngày giao dịch, DNSE có độ trễ dữ liệu theo mình quan sát là > 2 phút. Sau thời gian sử dụng và kiểm nghiệm nếu nguồn dữ liệu không đáng tin cậy thì mình sẽ khuyến nghị dùng cách khác.
