### ISSUE TITLE
Dữ liệu vnindex chỉ đến năm 2020

### ISSUE THREAD

**Issue by yellow1912** [thinh-vu/vnstock#97]
**Mô tả lỗi**
Mô tả một cách rõ ràng và ngắn gọn về lỗi.

stock_historical_data('VNINDEX', '2013-01-01', '2023-11-11', '1D, 'index')

Dữ liệu chỉ chạy đến ngày 5/11/2020. Lỗi này chỉ xảy ra với vnindex, các symbol khác vẫn có data cũ hơn.

**Comment by yellow1912** [comment]
Có vẻ như nếu dùng source là TCBS thì sẽ lấy được data dài hơn.

**Comment by thinh-vu** [comment]
Cám ơn bạn đã chia sẻ, nếu bạn có nhu cầu lấy dữ liệu VNINDEX trong khoảng thời gian dài thì dùng source TCBS thay vì DNSE nhé. Dữ liệu có thể lấy tới năm 2000 từ khi giao dịch chứng khoán VN. Có điều việc này cần chạy qua  nhiều vòng lặp (cụ thể 24 lần) nên sẽ mất thời gian. Trong thời gian tới mình cung cấp thêm các tùy chọn dữ liệu nâng cao với tốc độ tốt hơn trong gói Sponsor cho bạn nào cần.

![image](https://github.com/thinh-vu/vnstock/assets/39723360/0f77d1a8-f80d-4562-846e-ea179d9cd5e9)
