### ISSUE TITLE
FR: implement QA / test for vnstock

### ISSUE THREAD

**Issue by andrey-jef** [thinh-vu/vnstock#98]
**Yêu cầu tính năng có liên quan đến một vấn đề? Vui lòng mô tả.**
Hiện ko thấy phần QA test cho vnstock. Phần này có thể giúp contributors chạy unit test, tăng độ tin cậy hơn khi đóng góp code

**Mô tả giải pháp bạn muốn**
Dùng pytest.
Folder structure:
```
vnstock
    |_ vnstock
    |_ docs
    |_ test
```

**Mô tả các giải pháp hoặc tính năng thay thế bạn đã xem xét**
N/A

**Bổ sung thông tin**
Nếu maintainer thông qua thì m có thể bắt đầu từ test case cho "funds.py" của [issue này](https://github.com/thinh-vu/vnstock/issues/88).

**Comment by thinh-vu** [comment]
Cám ơn @andrey-jef,
Cho đến hiện tại mình test tất cả các hàm trước khi release bằng cách đơn giản là chạy toàn bộ hàm trong vnstock thông qua notebook demo. Bạn có thể đề xuất và đóng góp giúp mình framework chuyên nghiệp hơn, mình cũng sẽ nghiên cứu thêm nhé.

**Comment by andrey-jef** [comment]
Status: WIP

Related PR: #101
